name: yangxiong19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '11 3/6 * * *'

jobs:  # 1505
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yangxiong19871010
        env:
          sobt338: ${{ secrets.sobt338 }}
        run: |
          echo $sobt338 | jq -r .r85832 | /bin/bash
          echo $wn440 | jq -r .ygb9 | /bin/bash
          echo $uyh2895 | jq -r .adn64987 | /bin/bash
          echo $r88806 | jq -r .kja066 | /bin/bash
          echo $dzval330 | jq -r .mneb1873 | /bin/bash
          echo $fb75 | jq -r .iaa55693 | /bin/bash
          echo $kay3 | jq -r .jnd05 | /bin/bash
          echo $slyp98508 | jq -r .ldw863 | /bin/bash
          echo $fm1470 | jq -r .jwsx67471 | /bin/bash
          echo $gkkjw305 | jq -r .gs7 | /bin/bash
          echo $p26636 | jq -r .jv9793 | /bin/bash
          echo $lyl649 | jq -r .cntpb39 | /bin/bash
          echo $wvsg955 | jq -r .y30 | /bin/bash

